### ISSUE TITLE
Texture conversion

### ISSUE THREAD

**Issue by mdiBox** [IGI-Research-Devs/IGI-Editor#6]
Hello!

How can I convert .tex textures to another format?
The game should work with open .tga textures as far as I know.

**Comment by heaven-hm** [comment]
You can use `TGAConv` tool which i have created to convert `TGA` to `PNG`

[TGAConv Tool](https://github.com/Jones-HM/IGI-Research-Data/blob/main/Tools/TGAConv.zip)

Tools/TGaConv - is tool for Textures convertor for Objects like `wood_material.tex,concrete_bullet.tex` to convert to **PNG** format, usage</br>

### Convert texture to PNG: 
</br>`tgaconv.exe filename.tga -ToPng`
### Convert texture to TGA: 
</br>`tgaconv.exe filename.png -ToTga`

**Comment by mdiBox** [comment]
That's really cool!

I'm upscaling textures from old games. Hopefully the Project IGI engine can scale textures.

Thank you!
